GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/66d992bd3f63e9be9623f678

###
PUT http://localhost:3001/api/persons/66dfe7d4c3cb96879f3a0593
Content-Type: application/json

{
    "name": "Laddo",
    "phone": "1235"
}
###
DELETE http://localhost:3001/api/persons/66dfecba4878551fedc5a0a0

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "assdfh",
    "phone": "123"
}