GET https://fullstackopen-6b8m.onrender.com/info

###
GET https://fullstackopen-6b8m.onrender.com/api/persons/

###
GET https://fullstackopen-6b8m.onrender.com/api/persons/66e003e78d04e9c051109c3f

###
PUT https://fullstackopen-6b8m.onrender.com/api/persons/66e003e78d04e9c051109c3f
Content-Type: application/json

{
    "name": "Laddo",
    "phone": "1235"
}
###
DELETE https://fullstackopen-6b8m.onrender.com/api/persons/66e00487b71825502d3a7963

###
POST https://fullstackopen-6b8m.onrender.com/api/persons
Content-Type: application/json

{
    "name": "assdfh",
    "phone": "123"
}